-- Supabase/Postgres full schema migration for an empty database.
-- Run this once on a fresh Supabase database to create all tables used by JewelHub.

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE SCHEMA IF NOT EXISTS public;
SET search_path = public;

CREATE TABLE IF NOT EXISTS django_migrations (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	app varchar(255) NOT NULL,
	name varchar(255) NOT NULL,
	applied timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT django_migrations_app_name_uniq UNIQUE (app, name)
);

CREATE TABLE IF NOT EXISTS django_content_type (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	app_label varchar(100) NOT NULL,
	model varchar(100) NOT NULL,
	CONSTRAINT django_content_type_app_label_model_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS auth_permission (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(255) NOT NULL,
	content_type_id bigint NOT NULL REFERENCES django_content_type(id) ON DELETE CASCADE,
	codename varchar(100) NOT NULL,
	CONSTRAINT auth_permission_content_type_codename_uniq UNIQUE (content_type_id, codename)
);

CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_idx ON auth_permission (content_type_id);

CREATE TABLE IF NOT EXISTS auth_group (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(150) NOT NULL,
	CONSTRAINT auth_group_name_uniq UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS auth_group_permissions (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	group_id bigint NOT NULL REFERENCES auth_group(id) ON DELETE CASCADE,
	permission_id bigint NOT NULL REFERENCES auth_permission(id) ON DELETE CASCADE,
	CONSTRAINT auth_group_permissions_group_permission_uniq UNIQUE (group_id, permission_id)
);

CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_idx ON auth_group_permissions (group_id);
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_idx ON auth_group_permissions (permission_id);

CREATE TABLE IF NOT EXISTS auth_user (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	password varchar(128) NOT NULL,
	last_login timestamptz NULL,
	is_superuser boolean NOT NULL,
	username varchar(150) NOT NULL,
	first_name varchar(150) NOT NULL,
	last_name varchar(150) NOT NULL,
	email varchar(254) NOT NULL,
	is_staff boolean NOT NULL,
	is_active boolean NOT NULL,
	date_joined timestamptz NOT NULL,
	CONSTRAINT auth_user_username_uniq UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS auth_user_groups (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id bigint NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
	group_id bigint NOT NULL REFERENCES auth_group(id) ON DELETE CASCADE,
	CONSTRAINT auth_user_groups_user_group_uniq UNIQUE (user_id, group_id)
);

CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_idx ON auth_user_groups (user_id);
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_idx ON auth_user_groups (group_id);

CREATE TABLE IF NOT EXISTS auth_user_user_permissions (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id bigint NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
	permission_id bigint NOT NULL REFERENCES auth_permission(id) ON DELETE CASCADE,
	CONSTRAINT auth_user_user_permissions_user_permission_uniq UNIQUE (user_id, permission_id)
);

CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_idx ON auth_user_user_permissions (user_id);
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_idx ON auth_user_user_permissions (permission_id);

CREATE TABLE IF NOT EXISTS django_admin_log (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	action_time timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	object_id text NULL,
	object_repr varchar(200) NOT NULL,
	action_flag smallint NOT NULL CHECK (action_flag >= 0),
	change_message text NOT NULL,
	content_type_id bigint NULL REFERENCES django_content_type(id) ON DELETE SET NULL,
	user_id bigint NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_idx ON django_admin_log (content_type_id);
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_idx ON django_admin_log (user_id);

CREATE TABLE IF NOT EXISTS django_session (
	session_key varchar(40) PRIMARY KEY,
	session_data text NOT NULL,
	expire_date timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS django_session_expire_date_idx ON django_session (expire_date);

CREATE TABLE IF NOT EXISTS store_category (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title varchar(50) NOT NULL,
	slug varchar(55) NOT NULL,
	description text NOT NULL DEFAULT '',
	category_image varchar(100) NULL,
	is_active boolean NOT NULL,
	is_featured boolean NOT NULL,
	created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS store_product (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title varchar(150) NOT NULL,
	slug varchar(160) NOT NULL,
	sku varchar(255) NOT NULL,
	short_description text NOT NULL,
	detail_description text NULL,
	product_image varchar(100) NULL,
	price numeric(8, 2) NOT NULL,
	category_id bigint NOT NULL REFERENCES store_category(id) ON DELETE CASCADE,
	is_active boolean NOT NULL,
	is_featured boolean NOT NULL,
	created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT store_product_sku_uniq UNIQUE (sku)
);

CREATE INDEX IF NOT EXISTS store_product_category_id_idx ON store_product (category_id);

CREATE TABLE IF NOT EXISTS store_address (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id bigint NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
	locality varchar(150) NOT NULL,
	city varchar(150) NOT NULL,
	state varchar(150) NOT NULL
);

CREATE INDEX IF NOT EXISTS store_address_user_id_idx ON store_address (user_id);

CREATE TABLE IF NOT EXISTS store_cart (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id bigint NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
	product_id bigint NOT NULL REFERENCES store_product(id) ON DELETE CASCADE,
	quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
	created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS store_cart_user_id_idx ON store_cart (user_id);
CREATE INDEX IF NOT EXISTS store_cart_product_id_idx ON store_cart (product_id);

CREATE TABLE IF NOT EXISTS store_order (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id bigint NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
	address_id bigint NOT NULL REFERENCES store_address(id) ON DELETE CASCADE,
	product_id bigint NOT NULL REFERENCES store_product(id) ON DELETE CASCADE,
	quantity integer NOT NULL CHECK (quantity > 0),
	ordered_date timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status varchar(50) NOT NULL DEFAULT 'Pending',
	payment_status boolean NOT NULL DEFAULT FALSE,
	razorpay_order_id varchar(100) NULL,
	razorpay_payment_id varchar(100) NULL,
	razorpay_signature varchar(100) NULL
);

CREATE INDEX IF NOT EXISTS store_order_user_id_idx ON store_order (user_id);
CREATE INDEX IF NOT EXISTS store_order_address_id_idx ON store_order (address_id);
CREATE INDEX IF NOT EXISTS store_order_product_id_idx ON store_order (product_id);

CREATE TABLE IF NOT EXISTS store_payment (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(100) NOT NULL,
	phone varchar(10) NULL,
	email varchar(100) NOT NULL,
	modelselection varchar(20) NOT NULL,
	amount numeric(10, 2) NOT NULL,
	message text NOT NULL,
	order_id varchar(100) NOT NULL DEFAULT '',
	paid boolean NOT NULL DEFAULT FALSE,
	razorpay_payment_id varchar(100) NOT NULL DEFAULT '',
	razorpay_order_id varchar(100) NOT NULL DEFAULT '',
	razorpay_signature varchar(100) NOT NULL DEFAULT '',
	updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS store_payment_updated_at_idx ON store_payment (updated_at DESC);

